= Projektantrag

=== Idee
Applikation, mit welcher man Zeichensprache lernen und üben kann.

Hebt sich hervor durch KI, welche eigene Zeichen erkennen kann und die Genauigkeit dessen anzeigt.

Auch kann man das lesen üben, indem man Bilder von Zeichen mit deren Bedeutung verbindet.


=== Projektbeschreibung
Bei dem Projekt handelt es sich um eine Webanwendung in  welcher NutzerInnen Zeichensprache üben können. Dies vor allem durch zeigen von Handbewegungen/Handzeichen. Üblich ist momentan das Üben durch verbinden von Zeichen mit Bild/Text, bei diesem Projekt geht es vor allem um Üben mit eigenen Handbewegungen um den Lernprozess zu beschleunigen.

=== Nutzen
Durch die Applikation kann das Erlernen von Zeichensprache erheblich beschleunigt werden, da man selbst das "sprechen" in Zeichensprache üben kann.

=== Aufgabenbeschreibung
Die Definition of Done ist erfüllt, wenn NutzerInnen in der Applikation Bilder den zugehörigen Zeichen zuordnen können und selbst zeichen zu den geforderten Wörtern machen können, wobei diese bei bedarf korrigiert werden.

=== Umfeldanalyse/Neuigkeitsgehalt
Stand 22.04.2024 gibt es eine Hand voll ernsthafter Konkurrenten. Diese sind:

https://play.google.com/store/apps/details?id=com.lingvano.app&hl=en&gl=US[Lingvano]

Lingvano ist eine Österreichische Schule für Zeichensprache. Mit einem physischen Standort in Wien gehören sie zu den populärsten. Die App erfüllt eine Übungsfunktion. Die Übungsfunktion wird erfüllt durch Bilder, welche man mit deren Bedeutung in Zeichensprache verbinden muss oder simpler Satzbildung mit Bildern. **Keine** Übung gibt einem die Möglichkeit Zeichensprache **selbst zu üben**.

https://theaslapp.com[The ASL App]

The ASL App scheint eine populäre option in den USA zu sein. Mit noch weniger Funktionalität als Lingvano gibt es auch hier **keine** Möglichkeit zum selsbt üben mit Überprüfung.

https://play.google.com/store/apps/details?id=com.toleio.us[ASL Bloom]

Asl Bloom ist funktionsweise **ident** mit Lingvano.

=== Machbarkeit
Der schwierigste Aspekt des Projekts wäre die KI. Dieser wird jedoch stark erleichtert, da es einige Tutorials gibt, welche sich mit Action Recognition in Tensorflow intensiv beschäftigen (und wir haben die nächsten drei wochen quasi frei). https://www.youtube.com/watch?v=doDUihpj6ro&ab_channel=NicholasRenotte[(YT Video zu Action Recognition für Zeichensprache)]
