services:
  web:
    build: "./site/"
    ports:
      - "7859:7859"
    image: ital3x/ai-sign-language_web_dev:latest
    env_file:
      - ./site/.env.production
    external_links:
      - api
    restart: unless-stopped
    networks:
      - back-tier
      - front-tier
    pull_policy: always
  
  api:
    build: "./API/"
    env_file:
      - ./API/.env
    image: ital3x/ai-sign-language_api_dev:latest
    volumes:
      - db-data:/app/data/
    networks:
      - back-tier
    expose:
      - "5000"
    depends_on:
      - sqlite
    pull_policy: always
  
  auth:
    build: "./OAuthAPI/"
    env_file:
      - ./OAuthAPI/.env
    volumes:
      - db-accounts:/app/Data/
    networks:
      - back-tier
    expose:
      - "5001"
    
  tf-serving:
      build: "./TfServing/"
      image: ai-sign-language_tf_dev:latest
      ports:
          - "5002:8501"
      networks:
          - front-tier
      expose:
          - "8501"
        
volumes:
    db-data:
    db-accounts:

networks:
  back-tier: {}
  front-tier: {}