services:
  web:
    build: "./site/"
    ports:
      - "7859:7859"
    image: ital3x/ai-sign-language_web:latest
    env_file:
      - ./site/.env.production
    external_links:
        - asl-api
    restart: unless-stopped
    networks:
      - back-tier
      - front-tier
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
    pull_policy: always
    
  api:
    build: "./API/"
    env_file:
      - ./API/.env
    image: ital3x/ai-sign-language_api_dev:latest
    volumes:
      - db-data:/app/data/
    networks:
      - back-tier
    expose:
        - "5000"
    depends_on:
      - sqlite
    pull_policy: always
  
  sqlite:
    container_name: aisl-sqlite
    image: nouchka/sqlite3:latest
    volumes:
      - db-data:/app/data/
    restart: always

volumes:
    db-data:

networks:
  back-tier: {}
  front-tier: {}
