services:
  web:
    build: "./site/"
    ports:
      - "8080:8080"
    env_file:
      - ./site/.env
    links:
        - api
    networks:
      - back-tier
      - front-tier
      
  api:
    build: "./API/"
    env_file:
      - ./API/.env
    networks:
      - back-tier
    expose:
        - "5000"


networks:
  back-tier: {}
  front-tier: {}