@startuml
'https://plantuml.com/sequence-diagram

actor User as u
participant "Website" as W
u ->  W : "Login"
W -> API : "Login"


u -> W : "Start Lesson"
W -> VideoDevice : "Start camera"



@enduml