
### Get user with specific username
GET localhost:8080/api/user/Batman

### Get all users
GET {{url}}/api/user

### Create new user
POST localhost:8080/api/user
Content-Type: application/json

{
    "username": "batman"
}

### Delete user with specific username
DELETE localhost:8080/api/user/'batman'

