
### Get user with specific username
GET localhost:3000/api/user/John Doe

### Get all users
GET localhost:3000/api/user

### Create new user
POST localhost:3000/api/user
Content-Type: application/json

{
    "userName": "Batman",
    "profilePic":"https://www.google.com",
    "score":{
      "perfectlyDone":13,
      "dailyStreak": 5,
      "allTimeCorrect": 100
  }
}