
name: Docker Image API DEV 

on:
  push:
    branches: [ "stable-ai" ]
 

jobs:

  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
      
    - name: Get latest API version from Docker Hub
      run: bash .github/workflows/get-latest-version.sh ai-sign-language_tf_dev
    
    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
          
    - name: Build the Docker image API dev
      uses: docker/build-push-action@v4
      with:
        context: ./TfServing
        push: true
        tags: ital3x/ai-sign-language_tf_dev:${{ env.NEW_VERSION }},  ital3x/ai-sign-language_tf_dev:latest

