name: Node.js CI

on:
  push:
    branches: [ "main", "stable-api" ]
  pull_request:
    branches: [ "main", "stable-api" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: API/package-lock.json
      timeout-minutes: 20
    - name: Install dependencies and build
      working-directory: ./API
      run: |
        npm ci
        npm run build --if-present
      timeout-minutes: 20
    - name: Run tests
      working-directory: ./API
      run: npm test --if-present
